# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 10:21
from __future__ import unicode_literals

import bima_core.fields
import bima_core.permissions
import bima_core.storage
from django.db import migrations, models
import django.db.models.deletion
import drf_chunked_upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('bima_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Photo Type',
                'ordering': ('name',),
                'verbose_name_plural': 'Photo Types',
            },
            bases=(bima_core.permissions.ReadPermissionMixin, models.Model),
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos_type', to='bima_core.PhotoType', verbose_name='Type'),
        ),
    ]
