# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-25 15:28
from __future__ import unicode_literals

import bima_core.storage
from django.db import migrations, models
import django.db.models.deletion
import drf_chunked_upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('bima_core', '0002_auto_20170523_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos_type', to='bima_core.PhotoType', verbose_name='Type'),
        ),
    ]
