# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-29 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import drf_chunked_upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('bima_core', '0003_auto_20170525_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='damtaxonomy',
            name='code',
            field=models.CharField(blank=True, max_length=50, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='photochunked',
            name='file',
            field=models.FileField(max_length=255, null=True, upload_to=drf_chunked_upload.models.generate_filename),
        ),
        migrations.AlterField(
            model_name='photochunked',
            name='offset',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='photochunked',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Incomplete'), (2, 'Complete')], default=1),
        ),
    ]
