# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-03 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bima_core', '0004_auto_20170629_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damtaxonomy',
            name='slug',
            field=models.SlugField(max_length=200, verbose_name='slug'),
        ),
    ]
