# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-25 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bima_core', '0005_auto_20170703_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='upload_status',
            field=models.IntegerField(choices=[(0, 'Not uploaded'), (1, 'Uploading'), (2, 'Uploaded')], default=2, verbose_name='Upload status'),
        ),
    ]
