# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-27 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bima_core', '0006_photo_upload_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='upload_status',
            field=models.IntegerField(choices=[(0, 'Upload error'), (1, 'Uploading'), (2, 'Uploaded')], default=1, verbose_name='Upload status'),
        ),
    ]
