# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-28 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bima_core', '0007_auto_20170727_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='soundcloud_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='SoundCloud code'),
        ),
        migrations.AddField(
            model_name='photo',
            name='youtube_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='YouTube code'),
        ),
    ]
