# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-14 08:45
from __future__ import unicode_literals

import bima_core.fields
import bima_core.storage
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.manager
import drf_chunked_upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('bima_core', '0010_photo_vimeo_code'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='damtaxonomy',
            managers=[
                ('tree', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='photochunked',
            name='file',
            field=models.FileField(max_length=255, null=True, storage=bima_core.storage.FileSystemStorage(), upload_to=drf_chunked_upload.models.generate_filename),
        ),
        migrations.AlterField(
            model_name='taggedkeyword',
            name='language',
            field=bima_core.fields.LanguageField(choices=[('en', 'English')], default='en', max_length=3),
        ),
    ]
