# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-14 08:46
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.gis.geos import Point


def save_photo_points(apps, schema_editor):
    photo_model = apps.get_model("bima_core", "Photo")
    for photo in photo_model.objects.all():
        # Save photo in order that the new point field is set
        if photo.position:
            photo.point = Point(
                float(photo.position.longitude),
                float(photo.position.latitude)
            )
            photo.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bima_core', '0011_auto_20181114_0945'),
    ]

    operations = [
        migrations.RunPython(save_photo_points),
    ]
