# Generated by Django 3.2 on 2022-02-22 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('bima_core', '0012_auto_20181114_0946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='photoexif',
            options={'verbose_name': 'PhotoExif', 'verbose_name_plural': 'PhotoExifs'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('is_active', 'username', 'date_joined'), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelManagers(
            name='damtaxonomy',
            managers=[
                ('tree', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='album',
            name='description_ca',
        ),
        migrations.RemoveField(
            model_name='album',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='album',
            name='title_ca',
        ),
        migrations.RemoveField(
            model_name='album',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='damtaxonomy',
            name='name_ca',
        ),
        migrations.RemoveField(
            model_name='damtaxonomy',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='description_ca',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='title_ca',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='description_ca',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='title_ca',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='usageright',
            name='description_ca',
        ),
        migrations.RemoveField(
            model_name='usageright',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='usageright',
            name='title_ca',
        ),
        migrations.RemoveField(
            model_name='usageright',
            name='title_es',
        ),
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='covers_album', to='bima_core.photo', verbose_name='Cover'),
        ),
        migrations.AlterField(
            model_name='damtaxonomy',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='damtaxonomy',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='damtaxonomy',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='covers_gallery', to='bima_core.photo', verbose_name='Cover'),
        ),
        migrations.AlterField(
            model_name='gallerymembership',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_albums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='photos_album', to='bima_core.album', verbose_name='Album'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='author_photos', to='bima_core.photoauthor', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='copyright',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='copyright_photos', to='bima_core.copyright', verbose_name='Copyright'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='exif',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='bima_core.photoexif', verbose_name='EXIF'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='external_usage_restriction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='external_usage_restriction_photos', to='bima_core.usageright', verbose_name='External usage restriction'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='internal_usage_restriction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='internal_usage_restriction_photos', to='bima_core.usageright', verbose_name='Internal usage restriction'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='keywords',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='keyword_photos', through='bima_core.TaggedKeyword', to='taggit.Tag', verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='names',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='name_photos', through='bima_core.TaggedName', to='taggit.Tag', verbose_name='Names'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='photos', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='taggedkeyword',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bima_core_taggedkeyword_tags', to='taggit.tag'),
        ),
        migrations.AlterField(
            model_name='taggedname',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bima_core_taggedname_tags', to='taggit.tag'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
