# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-27 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VimeoAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('username', models.CharField(blank=True, help_text='Example: userZZZ', max_length=100, verbose_name='Username')),
                ('client_id', models.CharField(max_length=100, unique=True, verbose_name='Client ID')),
                ('client_secrets', models.CharField(max_length=200, unique=True, verbose_name='Client secrets')),
                ('access_token', models.CharField(help_text='Token must have at least scopes "public private create upload".', max_length=100, unique=True, verbose_name='Access token')),
            ],
            options={
                'verbose_name': 'Vimeo account',
                'ordering': ('name',),
            },
        ),
    ]
