# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-13 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Username')),
                ('client_secret', models.TextField(help_text='Content of client_secret.json for this Youtube account.', verbose_name='Client secret')),
            ],
            options={
                'ordering': ('username',),
                'verbose_name': 'Youtube account',
            },
        ),
        migrations.CreateModel(
            name='YoutubeChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=100, unique=True, verbose_name='Channel id')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('token', models.TextField(blank=True, help_text='Autorefresh JSON token from Google OAuth2', verbose_name='Token')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.YoutubeAccount', verbose_name='Youtube account')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Youtube channel',
            },
        ),
    ]
