# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-13 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubeaccount',
            name='username',
            field=models.CharField(help_text='Example: user@company.com', max_length=100, unique=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='youtubechannel',
            name='channel_id',
            field=models.CharField(help_text='Example: UCT0ndP9FPOea9dgPkqB74Pw', max_length=100, unique=True, verbose_name='Channel id'),
        ),
        migrations.AlterField(
            model_name='youtubechannel',
            name='name',
            field=models.CharField(help_text='Informative name for users.', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='youtubechannel',
            name='token',
            field=models.TextField(blank=True, help_text="Autorefresh JSON token from Google OAuth2, don't edit manually.", verbose_name='Token'),
        ),
    ]
