"""
Django settings for tests project.

Generated by 'django-admin startproject' using Django 1.10.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

from bima_core.constants import (DEFAULT_CONSTANCE, RQ_UPLOAD_QUEUE, RQ_HAYSTACK_PHOTO_INDEX_QUEUE,
                                 RQ_UPLOAD_YOUTUBE_QUEUE)


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%nv(yz!4(or&l5f*$6ed*^mw@79(^o=nq%m39h$(u-vx4k#f)2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []

SITE_ID = 1

# Application definition

INSTALLED_APPS = [
    'modeltranslation',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'bima_core',
    'bima_core.private_api',
    'bima_core.youtube',
    'bima_core.vimeo',

    'django_mptt_admin',
    'categories',
    'constance',
    'constance.backends.database',
    'rest_framework',
    'rest_framework.authtoken',
    'taggit',
]


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ':memory:',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            # insert additional TEMPLATE_DIRS here
            # ldapdti/templates', # optional (used in password change)
        ],
        'OPTIONS': {
            'context_processors': [
                "django.contrib.auth.context_processors.auth",
                "django.template.context_processors.debug",
                "django.template.context_processors.i18n",
                "django.template.context_processors.media",
                "django.template.context_processors.static",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.tz",
                'django.template.context_processors.request',
                'constance.context_processors.config',
            ],
            'loaders': [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ]
        },
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en'
LANGUAGES = [
    ('en', 'English'),
    ('es', 'Español'),
    ('ca', 'Catalan'),
]
MODELTRANSLATION_FALLBACK_LANGUAGES = ('en', 'es', 'ca')

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

# bima_core and its dependencies
GEOPOSITION_GOOGLE_MAPS_API_KEY = 'not needed'
AUTH_USER_MODEL = 'bima_core.User'
FILE_SYSTEM_MEDIA_URL = os.path.join(BASE_DIR, 'media')
ROOT_URLCONF = 'tests_project.project.urls'

# Haystack for advanced searches
HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.whoosh_backend.WhooshEngine',
        'PATH': "haystack_index",
    },
}
HAYSTACK_DEFAULT_OPERATOR = "OR"
HAYSTACK_SIGNAL_PROCESSOR = 'bima_core.signals.PhotoSignalProcessor'

_RQ_DEFAULT_QUEUE_CONFIG = {
    "HOST": "localhost",
    "PORT": 6379,
    "DB": 0,
    "PASSWORD": "",
    "DEFAULT_TIMEOUT": 500,
}
RQ_QUEUES = {
    RQ_UPLOAD_QUEUE: _RQ_DEFAULT_QUEUE_CONFIG,
    RQ_HAYSTACK_PHOTO_INDEX_QUEUE: _RQ_DEFAULT_QUEUE_CONFIG,
    RQ_UPLOAD_YOUTUBE_QUEUE: _RQ_DEFAULT_QUEUE_CONFIG,
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'bima_core.private_api.paginators.NumberPagination',
    'PAGE_SIZE': 20
}

# Constance
CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'
CONSTANCE_CONFIG = dict(DEFAULT_CONSTANCE)

PHOTO_TYPES_ENABLED = False
